<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'c115ff2e36bd11fe43b6a5a17f6995ab' => $baseDir . '/includes/template-loader.php',
    '3282c7f4bc969a6b5bc25ebfa56f7560' => $baseDir . '/includes/shortcode.php',
    '544c63f8b994565d88edebc33e1f4656' => $baseDir . '/includes/query.php',
    'd78c0c9e2fd47169484dc369c95ff11f' => $baseDir . '/includes/template-tags.php',
    'bb77c06cd3b88b84e9f252bb6cc03cea' => $baseDir . '/includes/functions.php',
    '932c996e9a9616e7d1a047c34ad8aee9' => $baseDir . '/includes/gallery.php',
    '35328ea0a4cab2ccdab17d44acfe97c7' => $baseDir . '/includes/settings.php',
    'e0d231ec45fcab13038e737f5e1167a7' => $baseDir . '/includes/taxonomy.php',
    '656179c3223cd45ee61a7f881c18ee7a' => $baseDir . '/includes/back-compat/deprecated.php',
);
