<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Related_Posts_By_Taxonomy' => $baseDir . '/includes/class-widget.php',
    'Related_Posts_By_Taxonomy_Cache' => $baseDir . '/includes/class-cache.php',
    'Related_Posts_By_Taxonomy_Debug' => $baseDir . '/includes/class-debug.php',
    'Related_Posts_By_Taxonomy_Defaults' => $baseDir . '/includes/class-defaults.php',
    'Related_Posts_By_Taxonomy_Lazy_Loading' => $baseDir . '/includes/class-lazy-loading.php',
    'Related_Posts_By_Taxonomy_Plugin' => $baseDir . '/includes/class-plugin.php',
    'Related_Posts_By_Taxonomy_Rest_API' => $baseDir . '/includes/class-rest-api.php',
);
