<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit72a557a18bcf6768a48721153e2487d2
{
    public static $files = array (
        'c115ff2e36bd11fe43b6a5a17f6995ab' => __DIR__ . '/../..' . '/includes/template-loader.php',
        '3282c7f4bc969a6b5bc25ebfa56f7560' => __DIR__ . '/../..' . '/includes/shortcode.php',
        '544c63f8b994565d88edebc33e1f4656' => __DIR__ . '/../..' . '/includes/query.php',
        'd78c0c9e2fd47169484dc369c95ff11f' => __DIR__ . '/../..' . '/includes/template-tags.php',
        'bb77c06cd3b88b84e9f252bb6cc03cea' => __DIR__ . '/../..' . '/includes/functions.php',
        '932c996e9a9616e7d1a047c34ad8aee9' => __DIR__ . '/../..' . '/includes/gallery.php',
        '35328ea0a4cab2ccdab17d44acfe97c7' => __DIR__ . '/../..' . '/includes/settings.php',
        'e0d231ec45fcab13038e737f5e1167a7' => __DIR__ . '/../..' . '/includes/taxonomy.php',
        '656179c3223cd45ee61a7f881c18ee7a' => __DIR__ . '/../..' . '/includes/back-compat/deprecated.php',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Related_Posts_By_Taxonomy' => __DIR__ . '/../..' . '/includes/class-widget.php',
        'Related_Posts_By_Taxonomy_Cache' => __DIR__ . '/../..' . '/includes/class-cache.php',
        'Related_Posts_By_Taxonomy_Debug' => __DIR__ . '/../..' . '/includes/class-debug.php',
        'Related_Posts_By_Taxonomy_Defaults' => __DIR__ . '/../..' . '/includes/class-defaults.php',
        'Related_Posts_By_Taxonomy_Lazy_Loading' => __DIR__ . '/../..' . '/includes/class-lazy-loading.php',
        'Related_Posts_By_Taxonomy_Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Related_Posts_By_Taxonomy_Rest_API' => __DIR__ . '/../..' . '/includes/class-rest-api.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit72a557a18bcf6768a48721153e2487d2::$classMap;

        }, null, ClassLoader::class);
    }
}
